### ISSUE TITLE
Bug: Cat displayed on first pass when alternate animal is selected

### ISSUE THREAD

**Issue by SeanKilleen** [Skud/writtenkitten#10]
This is just for future reference since I'm thinking about taking this on per #9.

Reproduction steps:

* Open site (using the version at http://writtenkitten.co/) 
* Start typing
* Change animal dropdown to non-kitten (e.g. "bunny")
* type to get to 100 words

Expected: Picture of a bunny
Actual: Picture of a kitten

**Comment by joshuawalcher** [comment]
Interesting - it's because on initial entry to the page it appears to be hard-coded to preload a kitten image. I will fix.

**Comment by SeanKilleen** [comment]
@joshuawalcher -- thanks! Given the state of this repo, I'm going to move this issue over to yours. Closing this one.

**Comment by SeanKilleen** [comment]
Closed in favor https://github.com/joshuawalcher/writtenkitten/issues/1
